### PR TITLE
Search for projects in subdirectories

### PR DESCRIPTION
**Pull request by kusma**
It's sometimes useful to build projects also located in subdirectories. So let's suggest those as well.

### CODE REVIEW

**Comment by kusma** [comment]
OK, this has some performance issues when called inside large directory structures, and is pretty much useless as-is.

**Comment by knatten** [comment]
Sorry, forgot about this one. That comment sounds like I shouldn't merge?

**Comment by kusma** [comment]
completion scripts needs to be quite fast, or else it just cripples the user-experience. So no, this is not a good idea, at least not in this shape.

**Comment by biochimia** [comment]
Could this work more in an incremental completion fashion? Say expose any .unosln files and immediate sub-directories (without checking their contents), and recursively (one level at a time) allow completion from there?

**Comment by kusma** [comment]
@biochimia: Yeah, I think that makes more sense.

**Comment by knatten** [comment]
I started looking into an incremental solution this morning, but got distracted. Will hopefully finish it on the train later today :)

**Pull request closed without merging**
